Ability to delete reading history
inorichi/tachiyomi pull request #3871
Opened 2020-10-01 07:40 UTC by ghostbear

Closes #1799

**What it does**
It adds the ability to delete all reading history with one button

2020-10-01 07:54 UTC, joseph619 commented
Could you also add an undo option for this? If some user does this by mistake/curiosity, they would lose all history if they didn't have auto backup enabled.

2020-10-01 08:12 UTC, ghostbear commented
> Could you also add an undo option for this? If some user does this by mistake/curiosity, they would lose all history if they didn't have auto backup enabled.

There is already a warning which warns users that the history data will be deleted before they confirm the deletion. And from how the restore backup works they could use it to restore history

2020-10-03 14:36 UTC, arkon requested changes

2020-10-03 14:36 UTC, arkon commented on app/src/main/res/values/strings.xml
> +    <string name="clear_history_completed">History deleted</string>
Can you group these with the other Advanced section strings, e.g. `battery_optimization_setting_activity_not_found`?

2020-10-03 14:36 UTC, arkon commented on app/src/main/res/values/strings.xml
> +    <string name="clear_history_confirmation">Are you sure? All history will be lost</string>
Nitpick: add a period at the end.

2020-10-03 14:36 UTC, arkon commented on app/src/main/res/values/strings.xml
> +    <string name="pref_clear_history_summary">Delete history for all manga</string>
"reading history"?

2020-10-03 14:54 UTC, merged